### ISSUE TITLE
Request for the Code & Trained Model

### ISSUE THREAD

**Issue by raviy0807** [littlejuyan/GLFF#1]
HI

Could you please provide any estimation on release of the code and trained model?

Many Thanks

**Comment by littlejuyan** [comment]
> 

Sure. As our work is still under the review so we plan to upload the code once we receive the reviews, may be in the early Feb, 2023.

**Comment by RCorvi** [comment]
Hi @littlejuyan, is there any update on this? I have seen that the paper is now published.

**Comment by chenyu1330** [comment]
Hi，please update the code

**Comment by littlejuyan** [comment]
Uploaded, thanks!
